language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '9'
script:
  - npm run dist
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
