dist: xenial
services:
  - xvfb
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
services:
  - docker  

# Use APT Addon to install Chrome
addons:
  chrome: stable

jobs:
  include:
    - stage: test
      script:
       -  xvfb-run --server-args="-screen 0 1024x768x24" npm run test
    - stage: build
      script:
       - npm run dist
#    - stage: "integration test"
#      script: 
#        - npm run start-int-test-server
#        - npm run int-test-ci
#        - npm run stop-int-test-server

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
