language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '9'
services:
  - docker  

jobs:
  include:
    - stage: build
      script:
  		- npm run dist
    - stage: "integration test"
      script: 
        - npm run start-int-test-server
        - npm run int-test
        - npm run stop-int-test-server

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
