= Rico Angular Adapter

== Usage

You need to have both https://github.com/rico-projects/rico-js[rico-js] and this library as dependency to be able to use this adapter.
This enables you, in case of a bugfix or extension of rico-js to benefit from it without an update in `rico-angular`.

== Example

Please find an example in the https://github.com/rico-projects/rico-samples[rico-samples repository].

== Handling

=== Run library tests

 `npm run test`

=== Run library integration tests

Prerequsite: Have Docker installed.

Then, have a integration tests server running using Docker:

 `npm run start-int-test-server`

It will start a docker image with a rico runtime with some remoting controllers mapped to port 8085.

Now *execute tests* with:

 `npm run int-test`

The tests will watch the source files and re-run upon changes.

Finally, you can stop the integration server with
 
 `npm run stop-int-test-server`

=== Packaging 

For packaging, the https://www.npmjs.com/package/ng-packagr[ng-packagr] is used via the angular tool chain configuted via `angular.json` file.

== Releases

Releases are done automatically with https://github.com/semantic-release/semantic-release/[semantic-release] when release-triggering commit is added to `master` branch. 

Commits are evaluated by their commit message (thats why we need to stick with the _commit message format_, see "Contributing"). Depending on `fix`, `feat` or `BREAKING CHANGES`, a _Patch_-, _Feature_- or _Breaking_ release is build and released.

A new release is automatically published on NPM and as a release on GitHub.

== Contributing

Please use https://semantic-release.gitbook.io/semantic-release/#commit-message-format[Commit message format] when contributing changes via a PR to this repository. (https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type[List of commit types to be used])

For all details on contributing to Rico, please refer to the https://github.com/rico-projects/rico[main repo].